# @package __global__

defaults:
  - encodec/default

encodec:
  causal: false

rvq:
  bins: 1024
  n_q: 8
  q_dropout: false

seanet:
  n_filters: 64
  lstm_bidirectional: true
  transformer_params:
    do_enc: true
    do_skip_connection: true
    drop_transformer_prob: 0.1
    drop_skip_connection_prob: 0.3
    do_dec: false
    enc_dim: ${seanet.dimension}
    hidden_size: 768
    num_hidden_layers: 8
    num_attention_heads: 16
    intermediate_size: 2048
    hidden_dropout_prob: 0.0
    max_frames_in_trans: 150  # 3 seconds
    overlap_frames: 50  # 1 second
    causal: ${encodec.causal}
