device: cuda
dtype: float32
autocast: false
autocast_dtype: bfloat16
seed: 2036
show: false
continue_from: null
execute_only: null
execute_inplace: false
benchmark_no_load: false
efficient_attention_backend: torch
num_threads: 1
mp_start_method: forkserver
label: null
logging:
  level: INFO
  log_updates: 10
  log_tensorboard: false
  log_wandb: true
tensorboard:
  with_media_logging: false
  name: null
  sub_dir: null
wandb:
  with_media_logging: true
  project: Semantic-Encodec
  name: null
  group: null
slurm:
  gpus: 4
  mem_per_gpu: 40
  time: 3600
  constraint: null
  partition: null
  comment: null
  setup: []
  exclude: ''
dora:
  dir: /checkpoint/${oc.env:USER}/experiments/audiocraft/outputs
  exclude:
  - device
  - wandb.*
  - tensorboard.*
  - logging.*
  - dataset.num_workers
  - eval.num_workers
  - special.*
  - metrics.visqol.bin
  - metrics.fad.bin
  - execute_only
  - execute_best
  - generate.every
  - optim.eager_sync
  - profiler.*
  - deadlock.*
  - efficient_attention_backend
  - num_threads
  - mp_start_method
  - '*batch_size*'
  use_rendezvous: false
  git_save: true
datasource:
  manifests_dir: .
  max_sample_rate: 16000
  max_channels: 1
  timit_p: 0.1
  train:
    timit: ${datasource.manifests_dir}/timit_train.jsonl
    librispeech: ${datasource.manifests_dir}/LibriSpeech_train.jsonl
  valid:
    timit: ${datasource.manifests_dir}/timit_test.jsonl
    librispeech: ${datasource.manifests_dir}/LibriSpeech_dev.jsonl
  evaluate:
    timit: ${datasource.manifests_dir}/timit_test.jsonl
    librispeech: ${datasource.manifests_dir}/LibriSpeech_test.jsonl
  generate:
    timit: ${datasource.manifests_dir}/timit_test.jsonl
    librispeech: ${datasource.manifests_dir}/LibriSpeech_test.jsonl
solver: compression_asr_phone
fsdp:
  use: false
  param_dtype: float16
  reduce_dtype: float32
  buffer_dtype: float32
  sharding_strategy: shard_grad_op
  per_block: true
profiler:
  enabled: false
deadlock:
  use: false
  timeout: 600
dataset:
  batch_size: 80
  num_workers: 10
  segment_duration: 3
  num_samples: null
  return_info: true
  shuffle: false
  sample_on_duration: true
  sample_on_weight: true
  min_segment_ratio: 0.5
  train:
    num_samples: 500000
    shuffle: true
    shuffle_seed: 0
    permutation_on_files: false
  valid:
    num_samples: 10000
  evaluate:
    num_samples: 10000
    batch_size: 32
    segment_duration: 1
  generate:
    num_samples: 32
    return_info: true
    batch_size: 8
    segment_duration: 10
  max_duration: null
  augmentin_flip_phase: true
checkpoint:
  save_last: true
  save_every: 25
  keep_last: 10
  keep_every_states: null
generate:
  every: 10
  path: samples
  audio:
    format: mp3
    strategy: clip
    sample_rate: ${sample_rate}
  lm:
    use_sampling: false
    temp: 1.0
    top_k: 0
    top_p: 0.0
  num_workers: 5
evaluate:
  every: 10
  num_workers: 5
  truncate_audio: null
  fixed_generation_duration: null
  metrics:
    base: true
    visqol: false
    sisnr: true
optim:
  epochs: 200
  updates_per_epoch: 2000
  lr: 0.0003
  optimizer: adam
  adam:
    betas:
    - 0.5
    - 0.9
    weight_decay: 0.0
  ema:
    use: true
    updates: 1
    device: ${device}
    decay: 0.99
  max_norm: 0.0
schedule:
  lr_scheduler: cosine
  step:
    step_size: null
    gamma: null
  exponential:
    lr_decay: null
  cosine:
    warmup: 4000
    lr_min_ratio: 0.0
    cycle_length: 1.0
  polynomial_decay:
    warmup: null
    zero_lr_warmup_steps: 0
    end_lr: 0.0
    power: 1
  inverse_sqrt:
    warmup: null
    warmup_init_lr: 0.0
  linear_warmup:
    warmup: null
    warmup_init_lr: 0.0
sample_rate: 16000
channels: 1
losses:
  adv: 4.0
  feat: 4.0
  l1: 0.1
  mel: 0.0
  msspec: 2.0
  sisnr: 0.0
balancer:
  balance_grads: true
  ema_decay: 0.999
  per_batch_item: true
  total_norm: 1.0
adversarial:
  every: 1
  adversaries:
  - msstftd
  adv_loss: hinge
  feat_loss: l1
l1: {}
l2: {}
mrstft:
  factor_sc: 0.5
  factor_mag: 0.5
  normalized: false
mel:
  sample_rate: ${sample_rate}
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  n_mels: 64
  f_min: 64
  f_max: null
  normalized: false
  floor_level: 1.0e-05
sisnr:
  sample_rate: ${sample_rate}
  segment: 5.0
msspec:
  sample_rate: ${sample_rate}
  range_start: 6
  range_end: 11
  n_mels: 64
  f_min: 64
  f_max: null
  normalized: true
  alphas: false
  floor_level: 1.0e-05
metrics:
  visqol:
    mode: audio
    bin: null
    model: tcdaudio14_aacvopus_coresv_svrnsim_n.68_g.01_c1.model
msstftd:
  in_channels: 1
  out_channels: 1
  filters: 32
  norm: weight_norm
  n_ffts:
  - 1024
  - 2048
  - 512
  - 256
  - 128
  hop_lengths:
  - 256
  - 512
  - 128
  - 64
  - 32
  win_lengths:
  - 1024
  - 2048
  - 512
  - 256
  - 128
  activation: LeakyReLU
  activation_params:
    negative_slope: 0.3
msd:
  in_channels: 1
  out_channels: 1
  scale_norms:
  - spectral_norm
  - weight_norm
  - weight_norm
  kernel_sizes:
  - 5
  - 3
  filters: 16
  max_filters: 1024
  downsample_scales:
  - 4
  - 4
  - 4
  - 4
  inner_kernel_sizes: null
  groups:
  - 4
  - 4
  - 4
  - 4
  strides: null
  paddings: null
  activation: LeakyReLU
  activation_params:
    negative_slope: 0.3
mpd:
  in_channels: 1
  out_channels: 1
  periods:
  - 2
  - 3
  - 5
  - 7
  - 11
  n_layers: 5
  kernel_size: 5
  stride: 3
  filters: 8
  filter_scales: 4
  max_filters: 1024
  activation: LeakyReLU
  activation_params:
    negative_slope: 0.3
  norm: weight_norm
auxiliary_tasks:
  phone_quant:
    apply: true
    task_type: linar_probing
    dataset: phones
    weight: 5
    connect_point: rvq_centroid
    probs_num: 1
  asr_quant:
    apply: true
    task_type: asr
    weight: 12
    connect_point: rvq_centroid
    probs_num: 1
    ctc_encoder_path: null
    hidden_dim: 512
    mode: lstm
compression_model: past
encodec:
  autoencoder: seanet
  quantizer: rvq
  sample_rate: ${sample_rate}
  channels: ${channels}
  causal: false
  renormalize: false
seanet:
  dimension: 128
  channels: ${channels}
  causal: ${encodec.causal}
  n_filters: 64
  n_residual_layers: 1
  ratios:
  - 8
  - 5
  - 4
  - 2
  activation: ELU
  activation_params:
    alpha: 1.0
  norm: weight_norm
  norm_params: {}
  kernel_size: 7
  residual_kernel_size: 3
  last_kernel_size: 7
  dilation_base: 2
  pad_mode: constant
  true_skip: true
  compress: 2
  lstm: 2
  lstm_bidirectional: true
  disable_norm_outer_blocks: 0
  decoder:
    trim_right_ratio: 1.0
    final_activation: null
    final_activation_params: null
  encoder: {}
  transformer_params:
    do_enc: true
    do_skip_connection: true
    drop_transformer_prob: 0.1
    drop_skip_connection_prob: 0.3
    do_dec: false
    enc_dim: ${seanet.dimension}
    hidden_size: 768
    num_hidden_layers: 8
    num_attention_heads: 16
    intermediate_size: 2048
    hidden_dropout_prob: 0.0
    max_frames_in_trans: 150
    overlap_frames: 50
    causal: ${encodec.causal}
rvq:
  n_q: 8
  q_dropout: false
  bins: 1024
  decay: 0.99
  kmeans_init: true
  kmeans_iters: 50
  threshold_ema_dead_code: 2
  orthogonal_reg_weight: 0.0
  orthogonal_reg_active_codes_only: false
no_quant: {}
