# @package __global__

datasource:
  manifests_dir: .
  max_sample_rate: 16000
  max_channels: 1

  timit_p: 0.1
  
  train: 
    timit: ${datasource.manifests_dir}/timit_train.jsonl
    librispeech: ${datasource.manifests_dir}/LibriSpeech_train.jsonl
  valid: 
    timit: ${datasource.manifests_dir}/timit_test.jsonl
    librispeech: ${datasource.manifests_dir}/LibriSpeech_dev.jsonl
  evaluate: 
    timit: ${datasource.manifests_dir}/timit_test.jsonl
    librispeech: ${datasource.manifests_dir}/LibriSpeech_test.jsonl
  generate: 
    timit: ${datasource.manifests_dir}/timit_test.jsonl
    librispeech: ${datasource.manifests_dir}/LibriSpeech_test.jsonl
